language: java
sudo: true
dist: trusty
jdk:
        - oraclejdk8
script: 
        - mvn clean verify -Dorg.slf4j.simpleLogger.defaultLogLevel=OFF

after_success:
        - mvn -pl '!build-common,!rapid-examples,!integration-tests' jacoco:report coveralls:report
